# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
expected_survival_term <- function(eta, ws, M, Sigma, weights, nodes, target_size = 128L, n_rep = 1L, use_adaptive = TRUE) {
    .Call(`_ghqCpp_expected_survival_term_to_R`, eta, ws, M, Sigma, weights, nodes, target_size, n_rep, use_adaptive)
}

